# GitHub Pages configuration for VTuber Game Documentation
title: VTuber Game - Live2D Framework Documentation
description: Comprehensive documentation for the Live2D VTuber Game framework with lipsync capabilities
url: "https://k-jadeja.github.io"
baseurl: "/vtubergame"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation structure
navigation:
  - title: "Home"
    url: /
  - title: "Getting Started"
    url: /getting-started/
  - title: "Architecture"
    url: /architecture/
  - title: "API Reference"
    url: /api/
  - title: "Development"
    url: /development/
  - title: "Examples"
    url: /examples/
  - title: "Troubleshooting"
    url: /troubleshooting/

# Social links
github_username: K-Jadeja
repository: K-Jadeja/vtubergame

# Content settings
show_excerpts: true
paginate: 5